version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "5000:3306"

  redis:
    image: redis:3.0
    ports:
      - 5001:6379
